//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionStatus
    {
        public int Id { get; set; }
        public string StatusName { get; set; }
        public string StatusLogo { get; set; }
        public int Connection_Id { get; set; }
        public int ConnectionId { get; set; }
    
        public virtual Connection Connection { get; set; }
        public virtual Connection Connection1 { get; set; }
    }
}
