//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mail()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Ratings = new HashSet<Rating>();
            this.Accounts = new HashSet<Account>();
        }
    
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string MailedBy { get; set; }
        public string MailSubject { get; set; }
        public string MailDate { get; set; }
        public string MailTime { get; set; }
        public string MailFlag { get; set; }
        public string MailAttachment { get; set; }
        public string MailCc { get; set; }
        public string MailBCc { get; set; }
        public string MailLink { get; set; }
        public string ReplyToEmail { get; set; }
        public int MailFlag1_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual MailFlag MailFlag1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
