//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Id { get; set; }
        public string TeamMemberName { get; set; }
        public string TeamGroupID { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
