//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingType
    {
        public int Id { get; set; }
        public string RatingTypeName { get; set; }
        public int Rating_Id { get; set; }
    
        public virtual Rating Rating { get; set; }
    }
}
