//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rating()
        {
            this.RatingTypes = new HashSet<RatingType>();
        }
    
        public int Id { get; set; }
        public string RatingCount { get; set; }
        public string WhoRated { get; set; }
        public string WhoIsRated { get; set; }
        public string RatingTime { get; set; }
        public int RatingTypeId { get; set; }
        public int AccountId { get; set; }
        public int CommentId { get; set; }
        public int MailId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual Mail Mail { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingType> RatingTypes { get; set; }
    }
}
